[package]
name = "cert"
version = "0.0.0"
edition = "2021"

[dependencies]
crypto = { version = "0.0.4", path = "../stable-packages/crypto-v0.0.4" }
rand_core = { version = "*", features = ["getrandom"] }
rand_chacha = "*"