[package]
name = "tspp"
version = "0.0.1"
edition = "2021"

[dependencies]
cryptopkg = { package = "crypto", version = "0.0.5", path = "../stable-packages/crypto-v0.0.5" }
rand_core = { version = "*", features = ["getrandom"] }
rand_chacha = "*"